const PRE_INTERN = [
  'kicad_pcb',
  'version',
  'generator',
  'general',
  'thickness',
  'setup',
  'pad_to_mask_clearance',
  'solder_mask_min_width',
  'grid_origin',
  'offset',
  'aux_axis_origin',
  'net_class',
  'clearance',
  'trace_width',
  'via_dia',
  'via_drill',
  'uvia_dia',
  'uvia_drill',
  'diff_pair_width',
  'diff_pair_gap',
  'add_net',
  'module',
  'footprint',
  'layer',
  'layers',
  'tedit',
  'tstamp',
  'at',
  'size',
  'descr',
  'tags',
  'path',
  'attr',
  'fp_text',
  'gr_text',
  'reference',
  'value',
  'user',
  'fp_line',
  'fp_circle',
  'fp_arc',
  'fp_rect',
  'fp_poly',
  'gr_line',
  'gr_circle',
  'gr_arc',
  'gr_rect',
  'gr_poly',
  'pad',
  'thru_hole',
  'smd',
  'connect',
  'np_thru_hole',
  'circle',
  'rect',
  'roundrect',
  'oval',
  'custom',
  'square',
  'drill',
  'net',
  'pin',
  'uuid',
  'tstamp',
  'model',
  'rotate',
  'xyz',
  'scale',
  'offset',
  'segment',
  'via',
  'zone',
  'filled_areas',
  'fill',
  'polygon',
  'pts',
  'xy',
  'keepout',
  'start',
  'end',
  'center',
  'mid',
  'radius',
  'width',
  'stroke',
  'type',
  'default',
  'dash_dot',
  'dashed',
  'solid',
  'locked',
  'free',
  'place',
  'yes',
  'no',
  'font',
  'face',
  'thickness',
  'bold',
  'italic',
  'justify',
  'left',
  'right',
  'center',
  'top',
  'bottom',
  'middle',
  'mirror',
  'hide',
  'effects',
  'property',
  'symbol',
  'lib_name',
  'lib_id',
  'extends',
  'graphic',
  'text',
  'pin_names',
  'pin_numbers',
  'offset',
  'in_bom',
  'on_board',
  'dnp',
  'exclude_from_sim',
  'electrical_type',
  'graphic_symbol',
  'power',
  'name',
  'number',
  'length',
  'hide',
  'rectangle',
  'circle',
  'arc',
  'polyline',
  'pt',
  'number',
  'name',
  'paper',
  'title_block',
  'title',
  'date',
  'rev',
  'company',
  'comment',
  'lib_symbols',
  'wire',
  'bus',
  'label',
  'global_label',
  'hierarchical_label',
  'no_connect',
  'junction',
  'bus_entry',
  'at',
  'pins',
  'pin',
  'schematic',
  'sheet',
  'sheet_file',
  'inst',
  'images',
  'image',
  'dimension',
  'dimension_format',
  'group',
  'members',
  'edge',
  'cutouts',
  'net',
  'node',
  'fp_lib_table',
  'sym_lib_table',
  'lib',
  'uri',
  'options',
  'descr',
  '3d_path',
  'copper_fill',
  'hatch',
  'thermal_gap',
  'thermal_bridge_width',
  'island_removal_mode',
  'smoothing',
  'radius',
  'solid',
  'none',
  'outline',
  'hatch_thickness',
  'min_thickness',
  'filled',
  'fill',
  'connect_pads',
  'thermal_bridge_angle',
  'front',
  'back',
  'line',
  'arc',
  'roundrect_rratio',
  'chamfer_ratio',
  'chamfer',
  'bottom_left',
  'bottom_right',
  'top_left',
  'top_right',
  'die_length',
  'zone_connect',
  'thermal_relief_gap',
  'thermal_relief_width',
  'solder_mask_margin',
  'solder_paste_margin',
  'solder_paste_ratio',
  'clearance',
  '铜皮',
  'edge.Cuts',
  'plot',
  'exclude_edgelayer',
  'plot_on_all_layers_selection',
  'exclude_pads_from_silkscreen',
  'plot_footprint_refs',
  'plot_footprint_values',
  'force_plot_invisible_refs_vals',
  'tenting',
  'front',
  'back',
  'teardrop',
  'best_width',
  'max_length',
  'max_height',
  'curved',
  'filter',
  'stackup',
  'copper_finish',
  'dielectric_constraints',
  'epsilon_r',
  'loss_tangent',
  'roughening',
  'image',
  'scale',
  'pos',
  'anchor',
  'corner_radius',
];

export class Sym {
  private static _cache = new Map<string, Sym>();
  private static _initialized = false;
  public readonly name: string;

  private constructor(name: string) {
    this.name = name;
  }

  static for(name: string): Sym {
    if (!Sym._initialized) {
      Sym._initialized = true;
      for (const n of PRE_INTERN) {
        const s = new Sym(n);
        Sym._cache.set(n, s);
      }
    }
    let s = Sym._cache.get(name);
    if (s === undefined) {
      s = new Sym(name);
      Sym._cache.set(name, s);
    }
    return s;
  }

  static isSym(value: unknown): value is Sym {
    return value instanceof Sym;
  }

  toString(): string {
    return this.name;
  }

  valueOf(): string {
    return this.name;
  }

  static clearInternCache(): void {
    Sym._cache.clear();
    Sym._initialized = false;
  }
}
