import fs from 'fs';

import { Ee3dModel } from '../easyeda/parametersEasyeda.js';
import { Ki3dModel } from './parametersKicadFootprint.js';

const VRML_HEADER = `#VRML V2.0 utf8
# 3D model generated by easyeda2kicad.py (https://github.com/uPesy/easyeda2kicad.py)
`;

function pythonRound(num: number, ndigits = 0) {
  const factor = Math.pow(10, ndigits);
  const n = num * factor;
  const floorN = Math.floor(n);
  const diff = n - floorN;
  const eps = 1e-12;

  if (Math.abs(diff - 0.5) < eps) {
    if (floorN % 2 === 0) {
      return floorN / factor;
    } else {
      return (floorN + 1) / factor;
    }
  } else {
    return Math.round(n) / factor;
  }
}

function getMaterials(objData: string) {
  const materialRegex = /newmtl[\s\S]*?endmtl/g;
  const matches = objData.match(materialRegex) || [];
  const materials: Record<string, any> = {};
  for (const match of matches) {
    const material: Record<string, any> = {};
    const lines = match.split(/\r?\n/);
    let materialId = '';
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.startsWith('newmtl')) {
        const parts = trimmed.split(/\s+/);
        materialId = parts[1];
      } else if (trimmed.startsWith('Ka')) {
        material['ambient_color'] = trimmed.split(/\s+/).slice(1);
      } else if (trimmed.startsWith('Kd')) {
        material['diffuse_color'] = trimmed.split(/\s+/).slice(1);
      } else if (trimmed.startsWith('Ks')) {
        material['specular_color'] = trimmed.split(/\s+/).slice(1);
      } else if (trimmed.startsWith('d')) {
        material['transparency'] = trimmed.split(/\s+/)[1];
      }
    }
    if (materialId) {
      materials[materialId] = material;
    }
  }
  return materials;
}

function getVertices(objData: string) {
  const vertices: string[] = [];
  const regex = /v (.*?)\n/g;
  let match;
  while ((match = regex.exec(objData)) !== null) {
    const coords = match[1].split(/\s+/);
    const rounded = coords
      .map((coord) => {
        const val = +coord / 2.54;
        const isNegZero = Object.is(val, -0);
        const isNeg = isNegZero || val < 0;
        const intPart = Math.trunc(val);
        const intPartIsEven = intPart % 2 === 0;
        const roundedNum = pythonRound(val, 4);

        if (isNeg && roundedNum === 0) {
          if (isNegZero) return '-0.0';
          return '0.0';
        }

        if (intPartIsEven) {
          const res = val.toFixed(4).replace(/\.?0+$/, '');
          if (+res === 0) {
            return isNegZero ? '-0.0' : '0.0';
          }
          if (Number.isInteger(+res)) {
            return (+res).toFixed(1);
          }
          return res;
        } else {
          if (Number.isInteger(roundedNum)) {
            return roundedNum.toFixed(1);
          }
          return roundedNum.toString();
        }
      })
      .join(' ');
    vertices.push(rounded);
  }
  return vertices;
}

function generateWrlModel(model3d: Ee3dModel) {
  if (!model3d.raw_obj)
    return new Ki3dModel({
      name: model3d.name,
      translation: null,
      rotation: null,
      raw_wrl: '',
    });
  const materials = getMaterials(model3d.raw_obj);
  const vertices = getVertices(model3d.raw_obj);

  let rawWrl = VRML_HEADER;
  const shapes = model3d.raw_obj.split('usemtl').slice(1);
  for (const shape of shapes) {
    const lines = shape.split(/\r?\n/);
    const matKey = lines[0].trim();
    const material = materials[matKey] || {
      diffuse_color: ['0.8', '0.8', '0.8'],
      specular_color: ['0.5', '0.5', '0.5'],
    };
    let indexCounter = 0;
    const linkDict: Record<string, number> = {};
    const coordIndex: string[] = [];
    const points: string[] = [];
    for (let i = 1; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line.length > 0) {
        const parts = line.replace(/\/\//g, ' ').split(/\s+/).slice(1);
        const face = parts.map((x: string) => parseInt(x, 10));
        const faceIndex: string[] = [];
        for (const index of face) {
          if (!(index in linkDict)) {
            if (vertices[index - 1]) {
              linkDict[index] = indexCounter;
              faceIndex.push(indexCounter.toString());
              points.push(vertices[index - 1]);
              indexCounter++;
            }
          } else {
            faceIndex.push(linkDict[index].toString());
          }
        }
        faceIndex.push('-1');
        coordIndex.push(faceIndex.join(',') + ',');
      }
    }
    if (points.length > 0) {
      points.splice(points.length - 1, 0, points[points.length - 1]);
    }

    const shapeStr = `
Shape{
    appearance Appearance {
        material  Material \t{
            diffuseColor ${material.diffuse_color.join(' ')}
            specularColor ${material.specular_color.join(' ')}
            ambientIntensity 0.2
            transparency 0
            shininess 0.5
        }
    }
    geometry IndexedFaceSet {
        ccw TRUE
        solid FALSE
        coord DEF co Coordinate {
            point [
                ${points.join(', ')}
            ]
        }
        coordIndex [
            ${coordIndex.join('')}
        ]
    }
}`;
    rawWrl += shapeStr;
  }
  return new Ki3dModel({
    name: model3d.name,
    translation: null,
    rotation: null,
    raw_wrl: rawWrl,
  });
}

class Exporter3dModelKicad {
  input: Ee3dModel;
  output: Ki3dModel | null;
  output_step: string | null;

  constructor(model3d: Ee3dModel) {
    this.input = model3d;
    this.output = model3d && model3d.raw_obj ? generateWrlModel(model3d) : null;
    this.output_step = model3d.step;
  }

  getWrlContent() {
    return this.output ? this.output.raw_wrl : null;
  }

  getStepContent() {
    return this.output_step ? Buffer.from(this.output_step) : null;
  }

  getAllContent() {
    return {
      name: this.output ? this.output.name : null,
      wrl: this.getWrlContent(),
      step: this.getStepContent(),
    };
  }

  export(libPath: string) {
    if (this.output) {
      const output = this.output;
      fs.writeFileSync(`${libPath}.3dshapes/${output.name}.wrl`, output.raw_wrl!, { encoding: 'utf-8' });
    }
    if (this.output_step) {
      fs.writeFileSync(`${libPath}.3dshapes/${this.output!.name}.step`, Buffer.from(this.output_step!), {
        encoding: 'binary',
      });
    }
  }
}

export { getVertices, generateWrlModel, Exporter3dModelKicad };
