export const minimalKicadPcb = `(kicad_pcb (version 20221018) (generator pcbnew)
  (general
    (thickness 1.6)
  )
  (layers
    (0 "F.Cu" signal)
    (31 "B.Cu" signal)
    (32 "B.Adhes" user)
    (33 "F.Adhes" user)
    (34 "B.Paste" user)
    (35 "F.Paste" user)
    (36 "B.SilkS" user)
    (37 "F.SilkS" user)
    (38 "B.Mask" user)
    (39 "F.Mask" user)
    (40 "Dwgs.User" user)
    (41 "Cmts.User" user)
    (42 "Eco1.User" user)
    (43 "Eco2.User" user)
    (44 "Edge.Cuts" user)
  )
  (net 0 "")
  (net 1 "VCC")
  (net 2 "GND")
  (net 3 "net1")
  (segment (start 10 10) (end 20 20) (width 0.25) (layer "F.Cu") (net 1))
  (gr_text "Hello" (at 50 50) (layer "F.SilkS")
    (effects (font (size 1.27 1.27) (thickness 0.15)))
  )
)`;

export const minimalKicadFootprint = `(footprint "Resistor_SMD:R_0603_1608Metric" (layer "F.Cu")
  (attr smd)
  (fp_text reference "R1" (at 0 -1.43) (layer "F.SilkS")
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value "10k" (at 0 1.43) (layer "F.Fab")
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (pad "1" smd roundrect (at -0.825 0) (size 0.8 0.95) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25))
  (pad "2" smd roundrect (at 0.825 0) (size 0.8 0.95) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25))
)`;

export const minimalKicadSymbol = `(kicad_symbol_lib (version 20211014) (generator kicad_symbol_editor)
  (symbol "Device:R"
    (pin passive line (at 0 3.81 90) (length 2.54)
      (name "1") (type passive)
    )
    (pin passive line (at 0 -3.81 270) (length 2.54)
      (name "2") (type passive)
    )
  )
)`;
